### ISSUE TITLE
Priors: Truncated Gaussian and log-normal

### ISSUE THREAD

**Issue by fzeiser** [anderkve/gambit_np#6]
@anderkve: Do you have a following priors implemented already somewhere?
- truncated Gaussian 
- log-normal

**Comment by anderkve** [comment]
The priors are here:

  https://github.com/anderkve/gambit_np/tree/master/ScannerBit/include/gambit/ScannerBit/priors
  https://github.com/anderkve/gambit_np/tree/master/ScannerBit/src/priors

There's a log-normal prior, but not a truncated Gaussian. I've never actually used the log-normal one, but it looks like it has YAML options as expected: "mu", "sigma", "base" and "cov_matrix".
